format_version: 10
pipelines:
  Second_Pipeline:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-899ce4c:
        git: https://github.com/shankarcs/gocd.git
        username: shankarcs
        shallow_clone: false
        auto_update: true
        branch: main
        encrypted_password: AES:tryeO6FjxPWWSX5MkxFVqw==:h37g5jamBbGz82OUFPowpIYj9aPXp08NkoS9X7z8vOU8RiwmRY0GcTDbUGWguc32
    stages:
    - Clone:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          git:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - Pipeline as code Second Pipeline
                command: echo
                run_if: passed
    parameters:
      Testing: Second Pipeline
